language: objective-c
osx_image: xcode8.3

before_install:
  - pod repo update

pods: remove_debug_pods
pods:
  rm -rf Pods
  bundle install
  bundle exec pod install

build:
  set -o pipefail && xctool test -workspace "Httper.xcworkspace" -scheme "Httper" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
